export default {
     STATUS_NEW: "NEW",
     STATUS_REQUEST: "REQUEST",
     STATUS_READY: "READY",
     STATUS_ACCEPT: "ACCEPT",
     STATUS_ONWAY: "ONWAY",
     STATUS_ONFRONT: "ONFRONT",
     STATUS_PICKUP: "PICKUP",
     STATUS_ARRIVING: "ARRIVING",
     STATUS_CAME: "CAME",
     STATUS_FINISH: "FINISH",
     STATUS_REJECT: "REJECT",
};